config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  resources :books
end
  

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
    @book = Book.new
  end

  def show
    @book =Book.find(params[:id])
  end

  def new
    @book = Book.new  
  end

  def create
    @books = Book.all
    @book = Book.new(book_params)
    if @book.save
      flash[:notice] = "Book was successfully created."
      redirect_to book_path(@book.id)
    else
      render :index
    end
  end
 
  def edit
    @book = Book.find(params[:id])
  end
  
  def update
    @book = Book.find(params[:id])#←show
    if @book.update(book_params)
      flash[:notice] = "Book was successfully updated."
      redirect_to book_path(@book)
    else
      render :edit
    end  
  end
  
  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end
  
  private
  def book_params
    params.require(:book).permit(:title, :body)#strong parameters
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>
<%= form_with model:@book, local:true do |f| %>
    <% if @book.errors.any? %>
      <%= @book.errors.count %>error prohibited this book from being saved:
      <% @book.errors.full_messages.each do |message| %>
        <%= message %>
      <% end %>
    <% end %> 

  <div class="field">
    <h4>title</h4>
    <%= f.text_field :title %>
  </div>
 
  <div class="field">
    <h4>Body</h4>
    <%= f.text_area :body %>
  </div>
       
  <div class="actions">
    <%= f.submit 'Update Book' %>
  </div>
  
<% end %>

<%= link_to "Show",book_path(@book.id) %>
   | 
<%= link_to "Back",books_path %>

app/views/books/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="books.sccs" >
    <title>Submit2</title>
  </head>
  <body>
    <h1>Books</h1>
    <table>
      <thead>
        <tr>
          <th>Title</th>    
          <th>Body</th>
          <td colspan="3"></td>
        </tr>  
      </thead>    
      <tbody>
      <% @books.each do |book| %>
        <tr>
          <td class="book-title"> <%= book.title %></td>
          <td class="book-body"> <%= book.body %></td>
          <td><%= link_to "Show", book_path(book.id) %></td>
          <td><%= link_to "Edit", edit_book_path(book.id) %></td>
          <td><%= link_to "Destroy", book_path(book.id), method: :delete,
                  data: { confirm: 'Are you sure?' } %></td> 
        </tr> 
      <% end %>
      </tbody>
    </table>
    
    <h2>New book</h2>
    <%= form_with model:@book, local:true do |f| %>
      <% if @book.errors.any? %>
        <%= @book.errors.count %>error prohibited this book from being saved:
        <% @book.errors.full_messages.each do |message| %>
          <%= message %>
        <% end %>
      <% end %>
      <div class="field">
        <h4>Title</h4>
        <%= f.text_field :title %>
      </div>
 
      <div class="field">
        <h4>Body</h4>
        <%= f.text_area :body %>
      </div>
       
      <div class="action">
        <%= f.submit 'Create Book' %>
      </div>
   <% end %>
  </body>  
</html>

app/views/books/show.html.erb
<%= flash[:notice] %>

<h4>Title:<%= @book.title %></h>
  
<h4>Body:<%= @book.body %></h4>

<p>
  <%= link_to "Edit",edit_book_path(@book.id) %>
   | 
  <%= link_to "Back",books_path %>
</p>

app/views/homes/index.html.erb
<h1>ようこそBookersへ！</h1>

<h4><p>Bookersでは、さまざまな書籍に関するあなたの意見や</p><br>
　　<p>印象を共有し交換することができます</p>
</h4>

<%= link_to "start","books" %>

app/views/homes/top.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Submit2</title>
  </head>
  <body>
    <h1>ようこそ<strong>Bookers</strong>へ！</h1>

    <p><strong>Bookers</strong>では、さまざまな書籍に関するあなたの意見や</p>
    <p>印象を共有し交換することができます</p>

    <p><%= link_to "Start", books_path %></p>
  </body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/8b4e452287.js" crossorigin="anonymous"></script>
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>